services:
  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - ml_api

  ml_api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
